version: '3.8'

services:
  rtsp-to-onvif:
    image: ghcr.io/connorgallopo/rtsp-to-onvif:latest
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config.yaml:/onvif.yaml
    environment:
      # Uncomment for verbose trace logging during setup
      # DEBUG: 1
